### ISSUE TITLE
Does this shell handle zombie processes which are running in the background?

### ISSUE THREAD

**Issue by jdxheikh** [Abdullahxz/gbsh#2]
Hey, Does this program handles the creation of zombie processes? In the readme it says that this shell supports the execution of background processes. How do you make sure they don't end up a zombie?

**Comment by Abdullahxz** [comment]
Yes, it does handle zombie processes. Let me explain in a bit more detail for you

Let's assume user has entered a command and wants to run it in the background. We first set a handler for SIGCHLD signal [here](https://github.com/Abdullahxz/gbsh/blob/main/gbsh.c#L54). After the fork here's how it's handled.

**childSignalHandler()**

- This function is used to handle the SIGCHLD signal, which is triggered when a child process terminates. It does not use the wait() function directly; instead, it uses waitpid() with the WNOHANG option in a loop to collect the exit status of terminated child processes.
- By using waitpid() with WNOHANG, the function reaps the status of any terminated child processes without blocking the main shell process, preventing them from becoming zombies. 

You can read more about this here https://linux.die.net/man/2/waitpid.
